/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Asteroid: typeof import('./src/components/planeGame/Asteroid.vue')['default']
    BaseComponent: typeof import('./src/components/BaseComponent.vue')['default']
    Bullet_1: typeof import('./src/components/planeGame/bullets/Bullet_1.vue')['default']
    CommonItem: typeof import('./src/components/planeGame/items/CommonItem.vue')['default']
    Dino: typeof import('./src/components/Dino.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    EnemyBullet_1: typeof import('./src/components/planeGame/enemies/EnemyBullet_1.vue')['default']
    EnemyPlane: typeof import('./src/components/planeGame/enemies/EnemyPlane.vue')['default']
    EnemyPlaneBig: typeof import('./src/components/planeGame/enemies/EnemyPlaneBig.vue')['default']
    EnemyPlaneBoss: typeof import('./src/components/planeGame/enemies/EnemyPlaneBoss.vue')['default']
    Engine: typeof import('./src/components/planeGame/Engine.vue')['default']
    ExtraLife: typeof import('./src/components/planeGame/items/ExtraLife.vue')['default']
    GamePage: typeof import('./src/components/GamePage.vue')['default']
    GamePause: typeof import('./src/components/planeGame/status/GamePause.vue')['default']
    GoogleGame: typeof import('./src/components/GoogleGame.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Life: typeof import('./src/components/Life.vue')['default']
    Obstacle: typeof import('./src/components/Obstacle.vue')['default']
    Plane: typeof import('./src/components/planeGame/Plane.vue')['default']
    PlaneGame: typeof import('./src/components/planeGame/PlaneGame.vue')['default']
    PowerUp: typeof import('./src/components/planeGame/items/PowerUp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shield: typeof import('./src/components/planeGame/shields/Shield.vue')['default']
    ShieldItem: typeof import('./src/components/planeGame/items/ShieldItem.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    Weapon: typeof import('./src/components/planeGame/weapons/Weapon.vue')['default']
  }
}
